name: adrop_ads_flutter
description: AdropAds flutter plugin that shows ads using native platform views
version: 1.7.0
publisher: dev@openrhapsody.com
homepage: https://adrop.io
repository: https://github.com/OpenRhapsody/adrop_ads_flutter

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4

flutter:
  plugin:
    platforms:
      android:
        package: io.adrop.adrop_ads
        pluginClass: AdropAdsFlutterPlugin
      ios:
        pluginClass: AdropAdsFlutterPlugin
